import { TreeData } from '../types/tree';

export const sampleTrees: Record<string, TreeData> = {
  techSupport: {
    id: 'sample_tech_support',
    name: 'Hardware Troubleshooting Decision Tree',
    growthDirection: 'TB',
    nodes: [
      {
        id: 'node_root',
        question: 'Is the computer powering on at all?',
        description: 'Check if fans spin, LEDs light up, or display turns on.',
        x: 400,
        y: 80,
        width: 270,
        height: 130,
        isRoot: true,
        type: 'question',
        color: '#3b82f6',
      },
      {
        id: 'node_screen_check',
        question: 'Is there any image visible on the monitor?',
        description: 'Look for BIOS splash, loading spinner, or backlight glow.',
        x: 180,
        y: 330,
        width: 270,
        height: 130,
        type: 'question',
        color: '#6366f1',
      },
      {
        id: 'node_power_led',
        question: 'Is the front power LED blinking or colored amber?',
        description: 'Observe motherboard or case indicator light codes.',
        x: 620,
        y: 330,
        width: 270,
        height: 130,
        type: 'question',
        color: '#f59e0b',
      },
      {
        id: 'node_boot_loop',
        question: 'Does it reach the operating system login screen?',
        description: 'Check if Windows/macOS/Linux finishes boot sequence.',
        x: 50,
        y: 580,
        width: 270,
        height: 130,
        type: 'question',
        color: '#06b6d4',
      },
      {
        id: 'node_monitor_cables',
        question: 'Inspect display cable connection & test another monitor.',
        description: 'Reseat HDMI/DisplayPort cable or try a different display.',
        x: 340,
        y: 580,
        width: 260,
        height: 120,
        type: 'outcome',
        color: '#10b981',
      },
      {
        id: 'node_outlet_check',
        question: 'Test power outlet with a lamp and verify power supply switch.',
        description: 'Ensure wall outlet has power and PSU switch is in I (ON) position.',
        x: 620,
        y: 580,
        width: 260,
        height: 120,
        type: 'outcome',
        color: '#ef4444',
      },
      {
        id: 'node_happy_login',
        question: 'Hardware is functioning normally! Proceed to user login.',
        description: 'System passed POST and booted successfully.',
        x: -80,
        y: 830,
        width: 260,
        height: 120,
        type: 'outcome',
        color: '#10b981',
      },
      {
        id: 'node_safe_mode',
        question: 'Boot into Safe Mode / Recovery Environment to repair OS.',
        description: 'Use startup repair or restore from system restore point.',
        x: 180,
        y: 830,
        width: 260,
        height: 120,
        type: 'outcome',
        color: '#f59e0b',
      },
    ],
    edges: [
      {
        id: 'edge_1',
        sourceNodeId: 'node_root',
        targetNodeId: 'node_screen_check',
        answer: 'Yes, powers on',
      },
      {
        id: 'edge_2',
        sourceNodeId: 'node_root',
        targetNodeId: 'node_power_led',
        answer: 'No, totally dead',
      },
      {
        id: 'edge_3',
        sourceNodeId: 'node_screen_check',
        targetNodeId: 'node_boot_loop',
        answer: 'Yes, monitor shows output',
      },
      {
        id: 'edge_4',
        sourceNodeId: 'node_screen_check',
        targetNodeId: 'node_monitor_cables',
        answer: 'No, screen is black',
      },
      {
        id: 'edge_5',
        sourceNodeId: 'node_power_led',
        targetNodeId: 'node_outlet_check',
        answer: 'No lights at all',
      },
      {
        id: 'edge_6',
        sourceNodeId: 'node_boot_loop',
        targetNodeId: 'node_happy_login',
        answer: 'Yes, login prompt appears',
      },
      {
        id: 'edge_7',
        sourceNodeId: 'node_boot_loop',
        targetNodeId: 'node_safe_mode',
        answer: 'No, blue screen or freeze',
      },
    ],
  },
  databaseSelector: {
    id: 'sample_db_selector',
    name: 'Database Architecture Selector',
    growthDirection: 'LR',
    nodes: [
      {
        id: 'db_root',
        question: 'What is the primary nature of your data schema?',
        description: 'Consider relation consistency and update patterns.',
        x: 80,
        y: 200,
        width: 270,
        height: 130,
        isRoot: true,
        type: 'question',
        color: '#8b5cf6',
      },
      {
        id: 'db_relational',
        question: 'Do you require multi-region automated sharding?',
        description: 'Evaluating distributed transactional scalability.',
        x: 470,
        y: 80,
        width: 270,
        height: 130,
        type: 'question',
        color: '#3b82f6',
      },
      {
        id: 'db_nonrelational',
        question: 'What is your primary document or access pattern?',
        description: 'Key-value caching vs JSON document trees.',
        x: 470,
        y: 330,
        width: 270,
        height: 130,
        type: 'question',
        color: '#06b6d4',
      },
      {
        id: 'db_spanner',
        question: 'Recommend: Google Cloud Spanner / CockroachDB',
        description: 'Globally distributed ACID relational database.',
        x: 860,
        y: 20,
        width: 260,
        height: 120,
        type: 'outcome',
        color: '#10b981',
      },
      {
        id: 'db_postgres',
        question: 'Recommend: PostgreSQL on Cloud SQL / Supabase',
        description: 'Proven rock-solid ACID relational standard.',
        x: 860,
        y: 160,
        width: 260,
        height: 120,
        type: 'outcome',
        color: '#10b981',
      },
      {
        id: 'db_firestore',
        question: 'Recommend: Firebase Firestore / MongoDB',
        description: 'Flexible nested JSON documents with real-time listeners.',
        x: 860,
        y: 290,
        width: 260,
        height: 120,
        type: 'outcome',
        color: '#10b981',
      },
      {
        id: 'db_redis',
        question: 'Recommend: Redis / KeyDB Memory Store',
        description: 'Ultra-low latency in-memory key-value caching.',
        x: 860,
        y: 430,
        width: 260,
        height: 120,
        type: 'outcome',
        color: '#10b981',
      },
    ],
    edges: [
      {
        id: 'e_rel',
        sourceNodeId: 'db_root',
        targetNodeId: 'db_relational',
        answer: 'Strict Relational / Tables',
      },
      {
        id: 'e_nosql',
        sourceNodeId: 'db_root',
        targetNodeId: 'db_nonrelational',
        answer: 'Dynamic / Unstructured',
      },
      {
        id: 'e_span',
        sourceNodeId: 'db_relational',
        targetNodeId: 'db_spanner',
        answer: 'Yes, Global scale needed',
      },
      {
        id: 'e_pg',
        sourceNodeId: 'db_relational',
        targetNodeId: 'db_postgres',
        answer: 'Standard single-region or cluster',
      },
      {
        id: 'e_doc',
        sourceNodeId: 'db_nonrelational',
        targetNodeId: 'db_firestore',
        answer: 'Rich Hierarchical Documents',
      },
      {
        id: 'e_cache',
        sourceNodeId: 'db_nonrelational',
        targetNodeId: 'db_redis',
        answer: 'Sub-millisecond Key-Value',
      },
    ],
  },
};
